apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mqtt
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883