#eclipse-mosquitto stimulator
services:

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"

  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: iot
      DOCKER_INFLUXDB_INIT_BUCKET: sensors
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-token

  ingestion:
    build: ./services/ingestion-service
    depends_on:
      - mqtt
      - influxdb