{
 "title": "Smart Home IoT Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"sensors\") |> range(start:-5m) |> filter(fn:(r)=>r._measurement==\"anomaly\" and r._field==\"anomaly\") |> last()"
    }
   ]
  },
  {
   "title": "Anomaly Score",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"sensors\") |> range(start:v.timeRangeStart) |> filter(fn:(r)=>r._measurement==\"anomaly\" and r._field==\"score\") |> aggregateWindow(every:v.windowPeriod, fn:mean)"
    }
   ]
  },
  {
   "title": "Anomaly Flag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"sensors\") |> range(start:v.timeRangeStart) |> filter(fn:(r)=>r._measurement==\"anomaly\" and r._field==\"anomaly\") |> aggregateWindow(every:v.windowPeriod, fn:last)\r\n"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"sensors\") |> range(start:-5m) |> filter(fn:(r)=>r._measurement==\"environment\" and r._field==\"temperature\") |> last()"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"sensors\") |> range(start:-5m) |> filter(fn:(r)=>r._measurement==\"environment\" and r._field==\"humidity\") |> last()"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket:\"sensors\") |> range(start:v.timeRangeStart, stop:v.timeRangeStop) |> filter(fn:(r)=>r._measurement==\"environment\" and r._field==\"humidity\") |> aggregateWindow(every:v.windowPeriod, fn:mean)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket:\"sensors\") |> range(start:v.timeRangeStart, stop:v.timeRangeStop) |> filter(fn:(r)=>r._measurement==\"environment\" and r._field==\"temperature\") |> aggregateWindow(every:v.windowPeriod, fn:mean)"
    }
   ]
  },
  {
   "title": "Temperature Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "query": "from(bucket:\"sensors\") |> range(start:v.timeRangeStart) |> filter(fn:(r)=>r._measurement==\"environment\" and r._field==\"temperature\")"
    }
   ]
  },
  {
   "title": "Latest Sensor Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "env = from(bucket:\"sensors\")\r\n  |> range(start:-10m)\r\n  |> filter(fn:(r)=>r._measurement==\"environment\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\r\n\r\nanom = from(bucket:\"sensors\")\r\n  |> range(start:-10m)\r\n  |> filter(fn:(r)=>r._measurement==\"anomaly\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\r\n\r\njoin(\r\n  tables: {env: env, anom: anom},\r\n  on: [\"_time\",\"device\"],\r\n  method: \"inner\"\r\n)\r\n|> keep(columns:[\"_time\",\"device\",\"temperature\",\"humidity\",\"score\",\"anomaly\"])"
    }
   ]
  }
 ]
}