apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
          - containerPort: 3000

        volumeMounts:

          - name: datasource
            mountPath: /etc/grafana/provisioning/datasources

          - name: dashboard-provider
            mountPath: /etc/grafana/provisioning/dashboards

          - name: dashboard
            mountPath: /var/lib/grafana/dashboards

      volumes:

        - name: datasource
          configMap:
            name: grafana-datasources

        - name: dashboard-provider
          configMap:
            name: grafana-dashboard-provider

        - name: dashboard
          configMap:
            name: grafana-dashboard