apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anomaly
  template:
    metadata:
      labels:
        app: anomaly
    spec:
      containers:
      - name: anomaly
        image: centraln/iot-anomaly:1.1